name: publish

on:
  push:
    tags:
      - 'v[1-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    uses: itplusx/github-workflows/.github/workflows/publish-typo3-extension.yml@main
    secrets:
      access-token: ${{ secrets.TYPO3_API_TOKEN }}
